package com.chrisjeffreys.photosharesite.datamodel;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import java.util.List;
import java.util.Objects;

@DynamoDBTable(tableName = "Memory-Jars")
public class MemoryJar {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String jarId;

    @DynamoDBAttribute
    private String owner;

    @DynamoDBAttribute
    private List<String> admins;

    @DynamoDBAttribute
    private List<String> viewers;

    @DynamoDBAttribute
    private String title;

    @DynamoDBAttribute
    private String description;

    @DynamoDBAttribute
    private List<Memory> memories;

    public MemoryJar() {
    }

    public MemoryJar(String owner, List<String> admins, List<String> viewers, String title, String description, List<Memory> memories) {
        this.owner = owner;
        this.admins = admins;
        this.viewers = viewers;
        this.title = title;
        this.description = description;
        this.memories = memories;
    }

    public String getJarId() {
        return jarId;
    }

    public void setJarId(String jarId) {
        this.jarId = jarId;
    }

    public String getOwner() {
        return owner;
    }

    public void setOwner(String owner) {
        this.owner = owner;
    }

    public List<String> getAdmins() {
        return admins;
    }

    public void setAdmins(List<String> admins) {
        this.admins = admins;
    }

    public List<String> getViewers() {
        return viewers;
    }

    public void setViewers(List<String> viewers) {
        this.viewers = viewers;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public List<Memory> getMemories() {
        return memories;
    }

    public void setMemories(List<Memory> memories) {
        this.memories = memories;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        MemoryJar memoryJar = (MemoryJar) o;
        return jarId.equals(memoryJar.jarId) && owner.equals(memoryJar.owner) && admins.equals(memoryJar.admins) && viewers.equals(memoryJar.viewers) && title.equals(memoryJar.title) && Objects.equals(description, memoryJar.description) && Objects.equals(memories, memoryJar.memories);
    }

    @Override
    public int hashCode() {
        return Objects.hash(jarId, owner, admins, viewers, title, description, memories);
    }
}
